### ISSUE TITLE
Failed to start sharing screen

### ISSUE THREAD

**Issue by rubinliudongpo** [rootkiwi/screen_share#1]
I followed your steps to get a release at MacOS.
At server side:
'''
$ ./screen_share_remote_go-0.1.1-darwin-amd64  screen_share_remote.conf 
2018/06/05 21:40:05 screen_share_remote started
2018/06/05 21:40:45 correct password by: 127.0.0.1:51239
'''
At client side:
'''
java  -jar screen_share-0.2.1-macos_x86_64.jar
'''
I can see following results, in fact, the port 8888 is not used by any other app.
![image](https://user-images.githubusercontent.com/22769865/40980116-4f10e6f2-690a-11e8-96b4-571733e5d061.png)

**Comment by rootkiwi** [comment]
hm, I dont have a mac and have not tested on mac, but I provided mac builds in hope that it would work

I would have guessed that the problem with mac would be the screen capture part,

but this, not sure if it have anything to do with mac or not,  maybe is a bug, will look into it and try to reproduce on linux soon

**Comment by rootkiwi** [comment]
so I see you try to use embedded and also remote server on localhost, what port do you use for remote web server?

**Comment by rootkiwi** [comment]
if you just want to share from the same computer, screen share remote is not needed

**Comment by rubinliudongpo** [comment]
my configuration:
port    (changeable): 50000
webPort (changeable): 8888

Thanks you feedback, I will try it at my Windows soon.
